[build]
  publish = "."

[[redirects]]
  from = "/"
  to = "/app/"
  status = 301

[[redirects]]
  from = "/app"
  to = "/app/"
  status = 301

[[redirects]]
  from = "/app/*"
  to = "/app/index.html"
  status = 200

# optional: fall back to root
[[redirects]]
  from = "/*"
  to = "/app/index.html"
  status = 200
